name: pull request labeler

on:
  pull_request: {}

jobs:
  labeler:
    name: Pull Request Labeler

    runs-on: ubuntu-latest

    steps:
      - name: Labeler
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
